### ISSUE TITLE
Problem with tomcatstats

### ISSUE THREAD

**Issue by pserrano** [aouyar/PyMunin#19]
Hi, I have a problem with this module, i try to work on a machine which tomcat7 ssl system, with all cfg ok, munin-node log print me this :

Service 'tomcatstats' exited with status 1/0.
 Error output from tomcatstats:
 EXCEPTION: %d format: a number is required, not str
Service 'tomcatstats' exited with status 1/0.

The config it's ok, all with env. on plugin dir, i had try make changes on cfg without ssl and comment this, also comment more parameters and all prompt same error. 

Thanks

Pablo

**Comment by doublehp** [comment]
This thread is dealing with the issue the wrong way. You are facing 
http://munin-monitoring.org/ticket/1162
which had been solved
http://munin-monitoring.org/ticket/1128
several days before this thread was open.

You would have found that if you had QUOTED your google keywords:
https://www.google.fr/search?newwindow=1&dcr=0&source=hp&ei=MpAdWqzkIYr6wAKtnayYBw&q=%22Insecure+directory+in+%24ENV%7BPATH%7D+while+running+with+-T+switch+at+%2Fusr%2Fshare%2Fperl5%2FMunin%2FNode%2FService.pm+line+215.%22&oq=%22Insecure+directory+in+%24ENV%7BPATH%7D+while+running+with+-T+switch+at+%2Fusr%2Fshare%2Fperl5%2FMunin%2FNode%2FService.pm+line+215.%22&gs_l=psy-ab.3...2062.3025.0.3366.4.3.0.0.0.0.136.136.0j1.1.0....0...1c.1.64.psy-ab..3.1.135.0..35i39k1.0.m1GXTYyFDkk

Solution proposed in http://munin-monitoring.org/ticket/863 worked for me; but is not the proper way to deal with this: it was a munin bug, and it ought to be reported upstream ...
